### ISSUE TITLE
[deploy] GitHub Pagesで画像が表示されない問題

### ISSUE THREAD

**Issue by getty708** [gdsc-osaka/ouac-web#1]
## エラーの内容
- GitHub pagesで公開した際に、`_nuxt` 以下が読み込まれない。

ブラウザのコンソールのエラー

```
gdsc-osaka.github.io/:4          GET https://gdsc-osaka.github.io/_nuxt/b423e2a.js net::ERR_ABORTED 404
gdsc-osaka.github.io/:4          GET https://gdsc-osaka.github.io/_nuxt/e219207.js net::ERR_ABORTED 404
gdsc-osaka.github.io/:4          GET https://gdsc-osaka.github.io/_nuxt/2a5c242.js net::ERR_ABORTED 404
gdsc-osaka.github.io/:4          GET https://gdsc-osaka.github.io/_nuxt/dc16070.js net::ERR_ABORTED 404
gdsc-osaka.github.io/:4          GET https://gdsc-osaka.github.io/_nuxt/040f944.js net::ERR_ABORTED 404
gdsc-osaka.github.io/:4          GET https://gdsc-osaka.github.io/_nuxt/af030df.js net::ERR_ABORTED 404
gdsc-osaka.github.io/:4          GET https://gdsc-osaka.github.io/_nuxt/0f1de5d.js net::ERR_ABORTED 404
```

**Comment by getty708** [comment]
@litchi7777 

この `<activity />` タグはどこにあるコンポーネントを指していますか？
エラーを吐いているように見えます。

https://github.com/gdsc-osaka/ouac-web/blob/fa856bae626538ccd9f5b59f656d3793c90c9595/sections/top/ActivitySection/template.html#L3


追記:
ヘッダーで使用するリンクのidを持っているだけの模様。idを別の場所に移動しました。

**Comment by litchi7777** [comment]
今確認したところ普通に映るようになっています
ありがとうございます！

**Comment by litchi7777** [comment]
結局原因はこのエラーなのでしょうか
ローカルでもこのエラーを見逃していた可能性はありますが画像が映らないということはなかったのですが
それとも画像の反映には時間がかかるとかあるのでしょうか

**Comment by getty708** [comment]
環境変数のエラーのようです。
generateコマンド実行時に環境変数 `DEPLOY_ENV` が読み込まれていない模様。

```html
<meta data-n-head="ssr" data-hid="og:image" property="og:image" content="https://gdsc-osaka.github.io/v.png">
```

https://github.com/gdsc-osaka/ouac-web/blob/790344ae6ab96db88a3b0186a5c01590f0a8d516/index.html#L4

**Comment by getty708** [comment]
windows環境でgenerateする場合は、 `npm run generate-win` を使用してください。
また以下のディスカッションも参照のこと

GDSC Osaka - Slack
https://gdsc-osaka.slack.com/archives/C0316FBD3HV/p1647222329200769

**Comment by getty708** [comment]
上のPRの確認&マージをお願いします。
また、 @litchi7777 の環境でも同じようにdeployできるか確認してもらえますか？

**Comment by litchi7777** [comment]
Windowsだったのでデフォルトのコマンドだとそもそも起動しなくて
一応  "generate-win": "SET DEPLOY_ENV=GH_PAGES && nuxt generate"
をscriptsに追加してgenerate-winを実行してもらって解決したはずなのですが上手く読み込めてないのでしょうか

**Comment by litchi7777** [comment]
自分の環境でdeployできるか検証してみます

**Comment by getty708** [comment]
git bashならうまくいくらしいという話もある。
windowsの環境変数わからなすぎる。。。

> generate-winを実行してもらって解決したはずなのですが上手く読み込めてないのでしょうか
わかったことあればここに追記してもらえますか？

**Comment by litchi7777** [comment]
windowsの自分がやってみて動くかで色々わかる気がするのでとりあえずやってみてここに報告します

**Comment by litchi7777** [comment]
$npm run generate-win
$npm run develop 
のみで特に問題なくpublishまで行えました

**Comment by litchi7777** [comment]
$npm run generate-win
$npm run deploy
を実行したところやはり画像が反映されない問題が起きました
環境変数をdeployのときにも与えるようにdeploy-winをつくってやってみます

**Comment by litchi7777** [comment]
cross-envを使用すると簡単に解決できそうです
自分はgit bashでもなぜか画像が表示されない問題が解決せず
npm install cross-env --save-dev
でcross-envをインストール
scriptに"generate:gh-pages": "cross-env DEPLOY_ENV=GH_PAGES nuxt generate"を追記

$npm run generate:gh-pages
$npm run deploy
を実行することで解決しました

-------------------------------------------------------------------------
Windows ユーザーの場合、 bash を使用していなければ、[cross-env](https://github.com/kentcdodds/cross-env) をインストールするといいかもしれません。

npm install cross-env --save-dev
そして、このように使用します:

  "build:gh-pages": "cross-env DEPLOY_ENV=GH_PAGES nuxt build",
  "generate:gh-pages": "cross-env DEPLOY_ENV=GH_PAGES nuxt generate"
  
  参考: https://develop365.gitlab.io/nuxtjs-2.8.X-doc/ja/faq/github-pages/

**Comment by litchi7777** [comment]
scriptsは最終的に以下のように変更しました
  "scripts": {
    "dev": "nuxt",
    "build": "DEPLOY_ENV=GH_PAGES nuxt build",
    "build-win": "cross-env DEPLOY_ENV=GH_PAGES nuxt build",
    "start": "nuxt start",
    "generate": "DEPLOY_ENV=GH_PAGES nuxt generate",
    "generate-win": "cross-env DEPLOY_ENV=GH_PAGES nuxt generate",
    "deploy": "gh-pages -d dist -t",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint:style": "stylelint \"**/*.{css,scss,sass,html,vue}\" --ignore-path .gitignore",
    "lint:prettier": "prettier --check .",
    "lint": "npm run lint:js && npm run lint:style && npm run lint:prettier",
    "lintfix": "prettier --write --list-different . && npm run lint:js -- --fix && npm run lint:style -- --fix"
  },
